---
- name: Install and Configure Jenkins
  hosts: webservers:dbservers
  become: yes
  tasks:
    - name: Update the APT package manager cache
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins official repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
